FROM python:3.11-slim
WORKDIR /app
RUN mkdir -p /app/infra/sessions
ENV PYTHONUNBUFFERED=1
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY common ./common
COPY backend ./backend
COPY worker ./worker
COPY sql ./sql
CMD ["python","-m","worker.runner"]
