FROM python:3.11-slim
WORKDIR /app
ENV PYTHONUNBUFFERED=1

# каталог для сессий (папка будет замонтирована с хоста)
RUN mkdir -p /app/infra/sessions

RUN apt-get update && apt-get install -y build-essential && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY common ./common
COPY backend ./backend
COPY worker ./worker
COPY sql ./sql

CMD ["python","-m","worker.runner"]
